//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortesEstoque.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao
    {
        public int Id { get; set; }
        public int ProdutoId { get; set; }
        public int UsuarioId { get; set; }
        public int EntidadeId { get; set; }
        public System.DateTime Data { get; set; }
        public string TipoMovimentacao { get; set; }
        public int Qtde { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Entidade Entidade { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual TipoMovimentacao TipoMovimentacao1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
