//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortesEstoque.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.ProdutoHistorico = new HashSet<ProdutoHistorico>();
            this.Movimentacao = new HashSet<Movimentacao>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Qtde { get; set; }
        public int GrupoId { get; set; }
    
        public virtual ICollection<ProdutoHistorico> ProdutoHistorico { get; set; }
        public virtual ICollection<Movimentacao> Movimentacao { get; set; }
        public virtual ProdutoGrupo ProdutoGrupo { get; set; }
    }
}
