//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortesEstoque.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMovimentacao
    {
        public TipoMovimentacao()
        {
            this.Movimentacao = new HashSet<Movimentacao>();
        }
    
        public string Tipo { get; set; }
        public string Descricao { get; set; }
        public string TipoTransacao { get; set; }
    
        public virtual ICollection<Movimentacao> Movimentacao { get; set; }
    }
}
